// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pliswlanuinhtllduomm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsaXN3bGFudWluaHRsbGR1b21tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjcxNzQsImV4cCI6MjA2MTM0MzE3NH0.hgUZVMSIHo31Ij5pQfTz-hankSjcWsPPZiSlWaKJf00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);